import 'package:flutter/material.dart';
import 'api_client.dart';
import 'kyc_screens.dart';
import 'screens/main_screen.dart';
import 'screens/waiting_page.dart';
import 'services/permission_service.dart';
import 'services/storage_service.dart';

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Will be generated by flutterfire configure
import 'services/fcm_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
    // Initialize Firebase with platform-specific options
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    await FcmService().init();
  } catch (e) {
    debugPrint('Error initializing Firebase: $e');
    debugPrint('Note: Make sure google-services.json is in android/app/ and firebase_options.dart exists');
  }
  runApp(const DriverApp());
}

class DriverApp extends StatefulWidget {
  const DriverApp({super.key});

  @override
  State<DriverApp> createState() => _DriverAppState();
}

class _DriverAppState extends State<DriverApp> {
  Widget _initialRoute = const LoginPage();
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _checkAuthState();
  }

  Future<void> _checkAuthState() async {
    try {
      final token = await StorageService.getToken();
      final driverId = await StorageService.getDriverId();
      
      if (token != null && token.isNotEmpty && driverId != null && driverId.isNotEmpty) {
        // Token exists, navigate to main screen
        setState(() {
          _initialRoute = MainScreen(token: token, driverId: driverId);
          _isLoading = false;
        });
      } else {
        // No token, show login page
        setState(() {
          _initialRoute = const LoginPage();
          _isLoading = false;
        });
      }
    } catch (e) {
      // On error, show login page
      setState(() {
        _initialRoute = const LoginPage();
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: Scaffold(
          body: Center(child: CircularProgressIndicator()),
        ),
      );
    }
    
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Driver Partner',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF2575FC)),
        useMaterial3: true,
        scaffoldBackgroundColor: const Color(0xFFF8F9FD),
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.white,
          surfaceTintColor: Colors.white,
          centerTitle: true,
          elevation: 0,
          titleTextStyle: TextStyle(
            color: Colors.black,
            fontSize: 18,
            fontWeight: FontWeight.w600,
          ),
          iconTheme: IconThemeData(color: Colors.black),
        ),
      ),
      home: _initialRoute,
    );
  }
}

class LoginPage extends StatefulWidget {
  const LoginPage({super.key});

  @override
  State<LoginPage> createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  final _phoneController = TextEditingController(text: '9944226010');
  final String _defaultName = 'Driver Tester';
  final String _defaultEmail = 'driver@test.com';
  final _otpController = TextEditingController();

  bool _loading = false;
  String? _otpHint;
  bool _useLoginFlow = true;
  String? _smsToken;
  String? _driverId;

  final _api = ApiClient(baseUrl: kApiBaseUrl);

  @override
  void dispose() {
    _phoneController.dispose();
    _otpController.dispose();
    super.dispose();
  }

  String _cleanPhone() {
    // Remove all non-digits and return clean phone number
    // Database stores phones without country code (e.g., 9944226010)
    final digits = _phoneController.text.replaceAll(RegExp(r'[^0-9]'), '');
    // Remove country code if present (91 prefix)
    if (digits.startsWith('91') && digits.length > 10) {
      return digits.substring(2); // Remove '91' prefix
    }
    return digits;
  }

  Future<void> _requestOtp() async {
    setState(() {
      _loading = true;
      _otpHint = null;
    });
    try {
      // Send phone without country code - backend will normalize it
      final phone = _cleanPhone();

      // Try login first (most users are existing drivers)
      try {
        final loginRes = await _api.sendLoginOtp(phone: phone);
        
        // If driver not found (404), throw to trigger signup flow
        if (loginRes.statusCode == 404) {
          throw Exception('Driver not found');
        }

        // Check if request was successful
        if (!loginRes.success) {
          throw Exception(loginRes.message.isNotEmpty 
              ? loginRes.message 
              : 'Failed to send OTP');
        }

        // Use body getter for type safety (ensures Map<String, dynamic>)
        final loginData = loginRes.body;
        final loginOtp = loginData['otp']?.toString();
        _smsToken = loginData['smsToken']?.toString();
        _driverId = loginData['driverId']?.toString();
        
        // Debug: Print response to help diagnose issues
        print('Login OTP Response: $loginData');
        print('SMS Token: $_smsToken');
        print('Driver ID: $_driverId');
        
        if (loginOtp != null && loginOtp.isNotEmpty) {
          _otpController.text = loginOtp;
          _otpHint = 'OTP (for testing): $loginOtp';
        }
        _useLoginFlow = true;
      } catch (e) {
        // If login fails (driver not found), try signup
        final errorMsg = e.toString().toLowerCase();
        if (errorMsg.contains('404') || errorMsg.contains('not found')) {
          // Clear any previous OTP to avoid confusion
          _otpController.clear();
          
          final signupRes = await _api.sendSignupOtp(
            phone: phone,
            name: _defaultName,
            email: _defaultEmail,
          );
          
          // Use body getter for type safety (ensures Map<String, dynamic>)
          final data = signupRes.body;
          final otp = data['otp']?.toString();
          _smsToken = data['smsToken']?.toString();
          _driverId = data['driverId']?.toString();
          
          // Debug: Print response to help diagnose issues
          print('Signup OTP Response: $data');
          print('SMS Token: $_smsToken');
          print('Driver ID: $_driverId');
          
          if (otp != null && otp.isNotEmpty) {
            _otpController.text = otp;
            _otpHint = 'OTP (for testing): $otp';
          }
          _useLoginFlow = false;
        } else {
          // Some other error, rethrow
          rethrow;
        }
      }
    } catch (e) {
      _showError(e);
    } finally {
      setState(() {
        _loading = false;
      });
    }
  }

  Future<void> _verifyOtp() async {
    setState(() {
      _loading = true;
    });
    try {
      // Use clean phone without country code - backend will normalize it
      final phone = _cleanPhone();
      final otpVal = _otpController.text.trim();

      ApiResult result;
      if (_useLoginFlow) {
        if (_smsToken == null) {
          throw Exception('SMS token not found. Please request OTP again.');
        }
        result = await _api.verifyLoginOtp(
          phone: phone,
          otp: otpVal,
          smsToken: _smsToken!,
          driverId: _driverId,
        );
        if (!result.success) {
          throw Exception(result.body['message'] ?? 'Login failed');
        }
      } else {
        if (_smsToken == null) {
          throw Exception('SMS token not found. Please request OTP again.');
        }
        // Get FCM token for signup verification (required by backend)
        String? fcmToken;
        try {
          fcmToken = await FcmService().getToken();
        } catch (e) {
          debugPrint('Error getting FCM token for signup: $e');
          // Use empty string if FCM token unavailable (backend requires it)
          fcmToken = '';
        }
        
        result = await _api.verifySignupOtp(
          phone: phone,
          otp: otpVal,
          smsToken: _smsToken!,
          fcmToken: fcmToken ?? '', // Backend requires this field
          name: _defaultName,
          email: _defaultEmail,
        );

        final msg = (result.body['message'] ?? '').toString().toLowerCase();
        if (!result.success && msg.contains('already exists')) {
          _useLoginFlow = true;
          // Re-request login OTP to get smsToken
          final loginRes = await _api.sendLoginOtp(phone: phone);
          if (loginRes.statusCode == 404) {
            throw Exception('Driver not found');
          }
          // Use body getter for type safety (ensures Map<String, dynamic>)
          final loginData = loginRes.body;
          _smsToken = loginData['smsToken']?.toString();
          _driverId = loginData['driverId']?.toString();
          
          // Debug: Print response to help diagnose issues
          print('Re-request Login OTP Response: $loginData');
          print('SMS Token: $_smsToken');
          
          if (_smsToken == null) {
            throw Exception('SMS token not found. Please request OTP again.');
          }
          result = await _api.verifyLoginOtp(
            phone: phone,
            otp: otpVal,
            smsToken: _smsToken!,
            driverId: _driverId,
          );
          if (!result.success) {
            throw Exception(result.body['message'] ?? 'Login failed');
          }
        } else if (!result.success) {
          throw Exception(result.body['message'] ?? 'Signup failed');
        }
      }

      // Backend returns: { success: true, message: "...", data: { driver: {...}, token: "...", refreshToken: "..." } }
      // Use body getter for type safety, then access the nested 'data' field
      final responseBody = result.body;
      final data = responseBody['data'] as Map<String, dynamic>? ?? {};
      
      // Debug: Print response to help diagnose issues
      print('========================================');
      print('Verify OTP Response: $responseBody');
      print('Data: $data');
      print('========================================');
      
      final token = data['token'] as String? ?? data['accessToken'] as String?;
      print('Token extracted: ${token != null ? "Found" : "Missing"}');
      if (token == null) {
        print('❌ ERROR: Token is null!');
        print('Full data keys: ${data.keys.toList()}');
        print('Response body keys: ${responseBody.keys.toList()}');
      }

      if (token != null && mounted) {
        final driver = (data['driver'] as Map<String, dynamic>?) ?? {};
        final driverId = driver['driverId']?.toString() ?? 'unknown';
        final refreshToken = data['refreshToken'] as String?;
        
        // Save token and driver data to local storage
        await StorageService.saveToken(token);
        if (refreshToken != null) {
          await StorageService.saveRefreshToken(refreshToken);
        }
        await StorageService.saveDriverId(driverId);
        await StorageService.saveDriverData(driver);
        await StorageService.savePhone(_phoneController.text.trim());
        
        print('Driver data: $driver');
        print('Driver keys: ${driver.keys.toList()}');
        
        // Driver model uses 'adminVerified' field: "Pending", "Approved", or "Rejected"
        // Backend returns "Approved" (capital A), convert to lowercase for comparison
        final adminVerifiedRaw = driver['adminVerified']?.toString() ?? '';
        final adminVerified = adminVerifiedRaw.toLowerCase();
        
        // Check document verification status
        final documentVerified = driver['documentVerified']?.toString().toLowerCase() ?? '';
        final profileVerified = driver['profileVerified']?.toString().toLowerCase() ?? '';
        
        // Debug: Print driver status
        print('========================================');
        print('Admin Verified (raw): "$adminVerifiedRaw"');
        print('Admin Verified (normalized): "$adminVerified"');
        print('Document Verified: "$documentVerified"');
        print('Profile Verified: "$profileVerified"');
        print('========================================');
        
        // Check if driver is approved (case-insensitive)
        // Also check if documents are accepted as fallback for KYC approved drivers
        final isApproved = adminVerified == 'approved' || 
                          adminVerifiedRaw == 'Approved' ||
                          (adminVerified.isEmpty && documentVerified == 'accepted' && profileVerified == 'accepted');
        
        if (isApproved) {
          print('✅ Driver approved (adminVerified: "$adminVerifiedRaw") - navigating to MainScreen');
          // Request permissions before navigating to main screen
          await _requestPermissions(context);
          
          // Update FCM token
          try {
            final fcmToken = await FcmService().getToken();
            if (fcmToken != null) {
              debugPrint('FCM Token to update: $fcmToken');
              // Send token to backend
              try {
                final updateResult = await _api.updateFCMToken(token: token, fcmToken: fcmToken);
                if (updateResult.success) {
                  debugPrint('✅ FCM token updated successfully on backend');
                } else {
                  debugPrint('⚠️ Failed to update FCM token: ${updateResult.body}');
                }
              } catch (e) {
                debugPrint('⚠️ Error updating FCM token on backend: $e');
                // Don't block login if FCM update fails
              }
            }
          } catch (e) {
            debugPrint('Error getting FCM token: $e');
          }

          if (mounted) {
            print('🚀 Navigating to MainScreen...');
            Navigator.of(context).pushAndRemoveUntil(
              MaterialPageRoute(
                builder: (_) => MainScreen(
                  token: token,
                  driverId: driverId,
                ),
              ),
              (route) => false,
            );
            print('✅ Navigation completed');
          } else {
            print('❌ Widget not mounted, cannot navigate');
          }
        } else if (adminVerified == 'rejected') {
          print('❌ Account rejected - navigating to WaitingPage');
          Navigator.of(context).push(
            MaterialPageRoute(
              builder: (_) => const WaitingPage(
                title: 'Account Rejected',
                message: 'Your account has been rejected. Please contact support.',
              ),
            ),
          );
        } else {
          print('⏳ Account pending - checking document status');
          // Driver status is pending - check document verification status
          if (documentVerified == 'accepted' || profileVerified == 'accepted') {
            print('📄 Documents verified - navigating to WaitingPage (Under Review)');
            // Documents submitted and verified, waiting for admin approval
            Navigator.of(context).push(
              MaterialPageRoute(
                builder: (_) => const WaitingPage(
                  title: 'Under Review',
                  message: 'Your documents have been submitted and are under admin review.\n\nYou will be notified once approved.',
                ),
              ),
            );
          } else {
            print('📝 Documents not verified - navigating to WelcomeScreen (KYC)');
            // Documents not submitted yet (pending/empty) - go to KYC flow
            Navigator.of(context).push(
              MaterialPageRoute(
                builder: (_) => WelcomeScreen(token: token),
              ),
            );
          }
        }
      } else if (token == null) {
        print('❌ ERROR: Token is null, cannot proceed');
        print('Response body: $responseBody');
        throw Exception(result.body['message'] ?? 'Token missing');
      } else if (!mounted) {
        print('❌ ERROR: Widget not mounted, cannot navigate');
      }
    } catch (e) {
      _showError(e);
    } finally {
      setState(() {
        _loading = false;
      });
    }
  }

  Future<void> _requestPermissions(BuildContext context) async {
    try {
      final messenger = ScaffoldMessenger.maybeOf(context);
      final permissionService = PermissionService();
      final results = await permissionService.requestPermissionsWithDialog(context);
      
      if (!mounted || messenger == null) return;

      final missing = <String>[];
      if (!results['location']!) missing.add('Location');
      if (!results['overlay']!) missing.add('Overlay');
      
      if (missing.isNotEmpty) {
        messenger.showSnackBar(
          SnackBar(
            content: Text('Some permissions are missing: ${missing.join(", ")}. Some features may not work.'),
            duration: const Duration(seconds: 4),
          ),
        );
      }
    } catch (e) {
      debugPrint('Error requesting permissions: $e');
      // Don't block login if permission request fails
    }
  }

  void _showError(Object e) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(e.toString())),
    );
  }

  @override
  Widget build(BuildContext context) {
    const primary = Color(0xFF2575FC);
    const background = Color(0xFFF5F7FB);
    return Scaffold(
      backgroundColor: background,
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 32),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const SizedBox(height: 16),
              Center(
                child: Container(
                  padding: const EdgeInsets.all(18),
                  decoration: BoxDecoration(
                    color: primary.withValues(alpha: 0.08),
                    borderRadius: BorderRadius.circular(16),
                  ),
                  child: const Icon(Icons.local_taxi, size: 42, color: primary),
                ),
              ),
              const SizedBox(height: 28),
              const Text(
                'Welcome Driver!',
                style: TextStyle(
                  fontSize: 26,
                  fontWeight: FontWeight.bold,
                  color: primary,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'Enter your mobile number to continue',
                style: TextStyle(
                  fontSize: 15,
                  color: Colors.grey.shade700,
                ),
              ),
              const SizedBox(height: 24),
              const Text(
                'Mobile Number',
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                  color: Color(0xFF0F172A),
                ),
              ),
              const SizedBox(height: 8),
              Container(
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(14),
                  border: Border.all(color: Colors.grey.shade300),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withValues(alpha: 0.03),
                      blurRadius: 8,
                      offset: const Offset(0, 4),
                    ),
                  ],
                ),
                child: Row(
                  children: [
                    const SizedBox(width: 12),
                    const Text('IN +91', style: TextStyle(fontSize: 16)),
                    const SizedBox(width: 12),
                    Expanded(
                      child: TextField(
                        controller: _phoneController,
                        keyboardType: TextInputType.phone,
                        decoration: const InputDecoration(
                          hintText: 'Enter mobile number',
                          border: InputBorder.none,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'We will send you a 6-digit OTP',
                style: TextStyle(
                  fontSize: 13,
                  color: Colors.grey.shade600,
                ),
              ),
              const SizedBox(height: 28),
              SizedBox(
                width: double.infinity,
                height: 54,
                child: ElevatedButton(
                  style: ElevatedButton.styleFrom(
                    backgroundColor: primary,
                    foregroundColor: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(14),
                    ),
                  ),
                  onPressed: _loading ? null : _requestOtp,
                  child: const Text(
                    'Get OTP',
                    style: TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
                  ),
                ),
              ),
              if (_otpHint != null) ...[
                const SizedBox(height: 12),
                Text(_otpHint!, style: const TextStyle(color: Colors.green)),
              ],
              const SizedBox(height: 24),
              const Text(
                'Enter OTP',
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                  color: Color(0xFF0F172A),
                ),
              ),
              const SizedBox(height: 8),
              TextField(
                controller: _otpController,
                keyboardType: TextInputType.number,
                decoration: const InputDecoration(
                  hintText: '6-digit OTP',
                ),
              ),
              const SizedBox(height: 16),
              SizedBox(
                width: double.infinity,
                height: 50,
                child: OutlinedButton(
                  onPressed: _loading ? null : _verifyOtp,
                  style: OutlinedButton.styleFrom(
                    side: const BorderSide(color: primary),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  child: const Text(
                    'Verify & Continue',
                    style: TextStyle(
                      color: primary,
                      fontWeight: FontWeight.w600,
                      ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
