import 'package:flutter/material.dart';
import 'api_client.dart';
import 'kyc_screens.dart';
import 'screens/main_screen.dart';
import 'screens/waiting_page.dart';
import 'services/permission_service.dart';

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Will be generated by flutterfire configure
import 'services/fcm_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
    // Initialize Firebase with platform-specific options
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    await FcmService().init();
  } catch (e) {
    debugPrint('Error initializing Firebase: $e');
    debugPrint('Note: Make sure google-services.json is in android/app/ and firebase_options.dart exists');
  }
  runApp(const DriverApp());
}

class DriverApp extends StatelessWidget {
  const DriverApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Driver Partner',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF2575FC)),
        useMaterial3: true,
        scaffoldBackgroundColor: const Color(0xFFF8F9FD),
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.white,
          surfaceTintColor: Colors.white,
          centerTitle: true,
          elevation: 0,
          titleTextStyle: TextStyle(
            color: Colors.black,
            fontSize: 18,
            fontWeight: FontWeight.w600,
          ),
          iconTheme: IconThemeData(color: Colors.black),
        ),
      ),
      home: const LoginPage(),
    );
  }
}

class LoginPage extends StatefulWidget {
  const LoginPage({super.key});

  @override
  State<LoginPage> createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  final _phoneController = TextEditingController(text: '9944226010');
  final String _defaultName = 'Driver Tester';
  final String _defaultEmail = 'driver@test.com';
  final _otpController = TextEditingController();

  bool _loading = false;
  String? _otpHint;
  bool _useLoginFlow = true;
  String? _smsToken;
  String? _driverId;

  final _api = ApiClient(baseUrl: kApiBaseUrl);

  @override
  void dispose() {
    _phoneController.dispose();
    _otpController.dispose();
    super.dispose();
  }

  String _cleanPhone() {
    // Remove all non-digits and return clean phone number
    // Database stores phones without country code (e.g., 9944226010)
    final digits = _phoneController.text.replaceAll(RegExp(r'[^0-9]'), '');
    // Remove country code if present (91 prefix)
    if (digits.startsWith('91') && digits.length > 10) {
      return digits.substring(2); // Remove '91' prefix
    }
    return digits;
  }

  Future<void> _requestOtp() async {
    setState(() {
      _loading = true;
      _otpHint = null;
    });
    try {
      // Send phone without country code - backend will normalize it
      final phone = _cleanPhone();

      // Try login first (most users are existing drivers)
      try {
        final loginRes = await _api.sendLoginOtp(phone: phone);
        
        // If driver not found (404), throw to trigger signup flow
        if (loginRes.statusCode == 404) {
          throw Exception('Driver not found');
        }

        final loginData = loginRes.data;
        final loginOtp = loginData['otp']?.toString();
        _smsToken = loginData['smsToken']?.toString();
        _driverId = loginData['driverId']?.toString();
        if (loginOtp != null && loginOtp.isNotEmpty) {
          _otpController.text = loginOtp;
          _otpHint = 'OTP (for testing): $loginOtp';
        }
        _useLoginFlow = true;
      } catch (e) {
        // If login fails (driver not found), try signup
        final errorMsg = e.toString().toLowerCase();
        if (errorMsg.contains('404') || errorMsg.contains('not found')) {
          // Clear any previous OTP to avoid confusion
          _otpController.clear();
          
          final signupRes = await _api.sendSignupOtp(
            phone: phone,
            name: _defaultName,
            email: _defaultEmail,
          );
          
          final data = signupRes.data;
          final otp = data['otp']?.toString();
          _smsToken = data['smsToken']?.toString();
          _driverId = data['driverId']?.toString();
          if (otp != null && otp.isNotEmpty) {
            _otpController.text = otp;
            _otpHint = 'OTP (for testing): $otp';
          }
          _useLoginFlow = false;
        } else {
          // Some other error, rethrow
          rethrow;
        }
      }
    } catch (e) {
      _showError(e);
    } finally {
      setState(() {
        _loading = false;
      });
    }
  }

  Future<void> _verifyOtp() async {
    setState(() {
      _loading = true;
    });
    try {
      // Use clean phone without country code - backend will normalize it
      final phone = _cleanPhone();
      final otpVal = _otpController.text.trim();

      ApiResult result;
      if (_useLoginFlow) {
        if (_smsToken == null) {
          throw Exception('SMS token not found. Please request OTP again.');
        }
        result = await _api.verifyLoginOtp(
          phone: phone,
          otp: otpVal,
          smsToken: _smsToken!,
          driverId: _driverId,
        );
        if (!result.success) {
          throw Exception(result.body['message'] ?? 'Login failed');
        }
      } else {
        if (_smsToken == null) {
          throw Exception('SMS token not found. Please request OTP again.');
        }
        result = await _api.verifySignupOtp(
          phone: phone,
          otp: otpVal,
          smsToken: _smsToken!,
          name: _defaultName,
          email: _defaultEmail,
        );

        final msg = (result.body['message'] ?? '').toString().toLowerCase();
        if (!result.success && msg.contains('already exists')) {
          _useLoginFlow = true;
          // Re-request login OTP to get smsToken
          final loginRes = await _api.sendLoginOtp(phone: phone);
          if (loginRes.statusCode == 404) {
            throw Exception('Driver not found');
          }
          final loginData = loginRes.data;
          _smsToken = loginData['smsToken']?.toString();
          _driverId = loginData['driverId']?.toString();
          if (_smsToken == null) {
            throw Exception('SMS token not found. Please request OTP again.');
          }
          result = await _api.verifyLoginOtp(
            phone: phone,
            otp: otpVal,
            smsToken: _smsToken!,
            driverId: _driverId,
          );
          if (!result.success) {
            throw Exception(result.body['message'] ?? 'Login failed');
          }
        } else if (!result.success) {
          throw Exception(result.body['message'] ?? 'Signup failed');
        }
      }

      final data = result.data;
      final token = data['token'] as String? ?? data['accessToken'] as String?;

      if (token != null && mounted) {
        final driver = (data['driver'] as Map<String, dynamic>?) ?? {};
        final status = driver['status']?.toString().toLowerCase() ?? '';
        final kyc = driver['kycStatus']?.toString().toLowerCase() ?? '';

        if (status == 'approved') {
          // Request permissions before navigating to main screen
          await _requestPermissions(context);
          
          // Update FCM token
          try {
            final fcmToken = await FcmService().getToken();
            if (fcmToken != null) {
              debugPrint('FCM Token to update: $fcmToken');
              // Send token to backend
              try {
                final updateResult = await _api.updateFCMToken(token: token, fcmToken: fcmToken);
                if (updateResult.success) {
                  debugPrint('✅ FCM token updated successfully on backend');
                } else {
                  debugPrint('⚠️ Failed to update FCM token: ${updateResult.body}');
                }
              } catch (e) {
                debugPrint('⚠️ Error updating FCM token on backend: $e');
                // Don't block login if FCM update fails
              }
            }
          } catch (e) {
            debugPrint('Error getting FCM token: $e');
          }

          if (mounted) {
          Navigator.of(context).pushAndRemoveUntil(
            MaterialPageRoute(
              builder: (_) => MainScreen(
                token: token,
                driverId: driver['driverId']?.toString() ?? 'unknown',
              ),
            ),
            (route) => false,
          );
          }
        } else if (status == 'rejected') {
          Navigator.of(context).push(
            MaterialPageRoute(
              builder: (_) => const WaitingPage(
                title: 'Account Rejected',
                message: 'Your account has been rejected. Please contact support.',
              ),
            ),
          );
        } else {
          // Driver status is pending - check KYC status
          if (kyc == 'submitted') {
            // KYC submitted, waiting for admin approval
            Navigator.of(context).push(
              MaterialPageRoute(
                builder: (_) => const WaitingPage(
                  title: 'Under Review',
                  message: 'Your KYC has been submitted and is under admin review.\n\nYou will be notified once approved.',
                ),
              ),
            );
          } else {
            // KYC not submitted yet (pending/empty) - go to KYC flow
            Navigator.of(context).push(
              MaterialPageRoute(
                builder: (_) => WelcomeScreen(token: token),
              ),
            );
          }
        }
      } else if (token == null) {
        throw Exception(result.body['message'] ?? 'Token missing');
      }
    } catch (e) {
      _showError(e);
    } finally {
      setState(() {
        _loading = false;
      });
    }
  }

  Future<void> _requestPermissions(BuildContext context) async {
    try {
      final messenger = ScaffoldMessenger.maybeOf(context);
      final permissionService = PermissionService();
      final results = await permissionService.requestPermissionsWithDialog(context);
      
      if (!mounted || messenger == null) return;

      final missing = <String>[];
      if (!results['location']!) missing.add('Location');
      if (!results['overlay']!) missing.add('Overlay');
      
      if (missing.isNotEmpty) {
        messenger.showSnackBar(
          SnackBar(
            content: Text('Some permissions are missing: ${missing.join(", ")}. Some features may not work.'),
            duration: const Duration(seconds: 4),
          ),
        );
      }
    } catch (e) {
      debugPrint('Error requesting permissions: $e');
      // Don't block login if permission request fails
    }
  }

  void _showError(Object e) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(e.toString())),
    );
  }

  @override
  Widget build(BuildContext context) {
    const primary = Color(0xFF2575FC);
    const background = Color(0xFFF5F7FB);
    return Scaffold(
      backgroundColor: background,
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 32),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const SizedBox(height: 16),
              Center(
                child: Container(
                  padding: const EdgeInsets.all(18),
                  decoration: BoxDecoration(
                    color: primary.withValues(alpha: 0.08),
                    borderRadius: BorderRadius.circular(16),
                  ),
                  child: const Icon(Icons.local_taxi, size: 42, color: primary),
                ),
              ),
              const SizedBox(height: 28),
              const Text(
                'Welcome Driver!',
                style: TextStyle(
                  fontSize: 26,
                  fontWeight: FontWeight.bold,
                  color: primary,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'Enter your mobile number to continue',
                style: TextStyle(
                  fontSize: 15,
                  color: Colors.grey.shade700,
                ),
              ),
              const SizedBox(height: 24),
              const Text(
                'Mobile Number',
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                  color: Color(0xFF0F172A),
                ),
              ),
              const SizedBox(height: 8),
              Container(
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(14),
                  border: Border.all(color: Colors.grey.shade300),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withValues(alpha: 0.03),
                      blurRadius: 8,
                      offset: const Offset(0, 4),
                    ),
                  ],
                ),
                child: Row(
                  children: [
                    const SizedBox(width: 12),
                    const Text('IN +91', style: TextStyle(fontSize: 16)),
                    const SizedBox(width: 12),
                    Expanded(
                      child: TextField(
                        controller: _phoneController,
                        keyboardType: TextInputType.phone,
                        decoration: const InputDecoration(
                          hintText: 'Enter mobile number',
                          border: InputBorder.none,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'We will send you a 6-digit OTP',
                style: TextStyle(
                  fontSize: 13,
                  color: Colors.grey.shade600,
                ),
              ),
              const SizedBox(height: 28),
              SizedBox(
                width: double.infinity,
                height: 54,
                child: ElevatedButton(
                  style: ElevatedButton.styleFrom(
                    backgroundColor: primary,
                    foregroundColor: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(14),
                    ),
                  ),
                  onPressed: _loading ? null : _requestOtp,
                  child: const Text(
                    'Get OTP',
                    style: TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
                  ),
                ),
              ),
              if (_otpHint != null) ...[
                const SizedBox(height: 12),
                Text(_otpHint!, style: const TextStyle(color: Colors.green)),
              ],
              const SizedBox(height: 24),
              const Text(
                'Enter OTP',
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                  color: Color(0xFF0F172A),
                ),
              ),
              const SizedBox(height: 8),
              TextField(
                controller: _otpController,
                keyboardType: TextInputType.number,
                decoration: const InputDecoration(
                  hintText: '6-digit OTP',
                ),
              ),
              const SizedBox(height: 16),
              SizedBox(
                width: double.infinity,
                height: 50,
                child: OutlinedButton(
                  onPressed: _loading ? null : _verifyOtp,
                  style: OutlinedButton.styleFrom(
                    side: const BorderSide(color: primary),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  child: const Text(
                    'Verify & Continue',
                    style: TextStyle(
                      color: primary,
                      fontWeight: FontWeight.w600,
                      ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
