-- Simple SQL to create a test booking
-- Run this directly in your PostgreSQL database

INSERT INTO bookings (
    "adminId",
    "name",
    "email",
    "phone",
    "pickup",
    "drop",
    "pickupDateTime",
    "serviceType",
    "vehicleType",
    "status",
    "type",
    "paymentMethod",
    "paymentStatus",
    "estimatedAmount",
    "discountAmount",
    "finalAmount",
    "advanceAmount",
    "upPaidAmount",
    "distance",
    "assignAllDriver",
    "driverAccepted",
    "createdBy",
    "startOtp",
    "endOtp",
    "createdAt",
    "updatedAt"
) VALUES (
    'admin-1',
    'Test Customer',
    'test@example.com',
    '91 987654',
    'Test Pickup Location, Test City',
    'Test Drop Location, Test City',
    NOW() + INTERVAL '2 hours',
    'One way',
    'Sedan',
    'Booking Confirmed',
    'Manual',
    'Cash',
    'Unpaid',
    500,
    0,
    500,
    0,
    500,
    10,
    true,
    'pending',
    'Admin',
    '1234',
    '5678',
    NOW(),
    NOW()
)
RETURNING "bookingId", "id", "adminId", "status", "assignAllDriver", "driverAccepted", "pickup", "drop", "finalAmount";

